version: '2'
services:
  db:
    build: ./SQL
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: patients
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    container_name: golang_db
    ports:
      - "3306:3306"
    tty: true

  # app:
  #   build: ./
  #   container_name: golang_app
  #   ports:
  #     - "8080:8080"
  #   tty: true
  #   depends_on:
  #     - db
  #   links:
  #     - db

  # web:
  #   build: ./webapp
  #   container_name: golang_web
  #   ports:
  #     - "10001:10001"
  #   depends_on:
  #     - app
  #     - db
  #   links:
  #     - app
  #     - db
